name: kvaser python wheels

on:
  push:
    # branches-ignore:
      # - develop
    branches:
      - deploy

jobs:
  linux_build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.9]
    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
        with:
          access_token: ${{ github.token }}
      - name: Checkout repository incl. submodules
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip twine
      - name: Build source package
        run: |
          python3 setup.py sdist
          python3 setup.py bdist_wheel
      - name: Upload to PyPi
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TOKEN }}
        run: |
          python3 -m pip install --use-feature=2020-resolver -U setuptools twine
          python3 -m twine upload dist/*.tar.gz
          python3 -m twine upload dist/*.whl
